### ISSUE TITLE
total is always halved

### ISSUE THREAD

**Issue by basharaq** [laithGh95/Assignment-10#5]
https://github.com/laithGh95/Assignment-10/blob/830ac3b91047b46ec9553a9d0db99c1d6f35a040/task-3_average_numbers/app.js#L17

shouldn't the total be divided by the length of the array? ;)
also, i like that you are reading about array functions such as reduce. however, i noticed in task 6 that you had an opportunity to use reduce() but didn't. this makes me wonder if you fully understand reduce() and when to use it. this is why i propose a small challenge :)

if you can explain to me here in a comment what reduce() does and when exactly we use it i will be comfortable that you understand it. otherwise you will have to solve the task using only loops and if statements ;)

**Comment by laithGh95** [comment]
We use the reduce method to loop on all items in an array to get a single value from the array depending on the operation we use, the return value can be number, array, etc.

For example, if we want to know the sum of numbers we can use reduce.
const numbers = [1, 2, 3, 4, 5];
let sum = numbers.reduce((total, num) => total + num);

Total is the value that will return and assign to the sum variable.

Here the returned value from reduce is number.

**Comment by basharaq** [comment]
very good Laith. you nailed it :D

**Comment by basharaq** [comment]
BTW Laith, you didn't have to use foreach for the average. using reduce and other array methods like map, filter, etc. is actually the best practice. in the near future i will demand all of you to only use those functions and not use for loops at all (you will still need to use while for some cases). i just want you to get used the concept of loops first :)

**Comment by laithGh95** [comment]
Thank you Bashar for your feedback.
Well, at this time I will just use for and while loops.
